<?php
/*
 * GRAB LAYOUT INFO SET IN THE PRIMARY VIEW
 */
$children = $this->viewModel()->getCurrent()->getChildren();
$child = null;
if (isset($children[0])):
	$child = $children[0]; 
endif;
$extra_main_content_class = "";
$home_dashboard_view = "demand";
if ($child != null && isset($child->dashboard_view)):
	$home_dashboard_view = $child->dashboard_view;
endif;

$home_link = $home_dashboard_view;
if ($home_link == "account"):
	$home_link = "users/" . $home_dashboard_view;
elseif ($home_link == "login" || $home_link == "company"):
	$home_link = "";
endif;

if ($child != null && isset($child->center_class)):
	$extra_main_content_class = " " . $child->center_class;
endif;

$user_name = $user_data = $userRole = null;
if(isset($child->user_identity)):
	//$user_name = strtoupper($child->user_identity->getUsername());
	
	$user_data = unserialize($child->user_identity->serialize());
	$user_name = strtoupper($user_data->user_fullname);
	
	$userRole = $child->user_identity->getRoles();
	$userRole = $userRole[0];
endif;
echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
<?php echo $this->headTitle('NGINAD RTB Portal')->setSeparator(' - ')->setAutoEscape(false) ?><?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
<!-- Le styles -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath() . '/images/favicon.png'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($this->basePath() . '/css/dev.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/menu/responsivemobilemenu.css')
                        ->prependStylesheet($this->basePath() . '/css/default.dashboard.css');
        ?>

<!-- Scripts -->
<?php echo $this->headScript()->prependFile($this->basePath() . '/js/3rdparty/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/3rdparty/jquery.validate.min.js')
                                      ->prependFile($this->basePath() . '/js/3rdparty/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/menu/responsivemobilemenu.js')
                                      ->prependFile($this->basePath() . '/js/3rdparty/jquery-1.11.1.min.js');

                                       ?>
<!--<link href='//fonts.googleapis.com/css?family=Cabin' rel='stylesheet' type='text/css'>-->
<link href='//fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
</head>
<body class="demand-dashboard">
<div class="top">
    <div class="container">
    	<?php //echo '<pre>'; print_r($user_data); exit;?>
        <a class="brand" href="/<?php echo $home_link; ?>"> <img src="/images/nginad_logo.png" class="logo-img" /></a>
       <?php if ($this->Login_bool() == true):?>
        <div class="pull-right user">
            	Logged in as <strong> <a class="blue" href="/users/account"><?php echo $user_data->user_login;?> ( <?php echo $user_data->user_email;?> )</a></strong> <a class="red" href="<?php echo $this->url('login/process', array('action'=>'logout')); ?>" >Logout</a>
        </div>
        <?php endif;?>
    </div>
</div>
	<div class="topmenu">
    	<div class="container">
        <div class="rmm" data-menu-style = "sapphire">
             <ul>
              <?php if ($this->Login_bool() == false):?>
              <li class="<?php if($home_dashboard_view == "signup") echo "active";?>"><a class="navlink" href="/signup">Signup</a></li>
              <li class="divider-vertical"></li>
              <?php else:?>
              <?php if (($user_data != null && $user_data->DemandCustomerInfoID != null) || $userRole=='admin' || $userRole=='superadmin'): ?>
              <li class="<?php if($home_dashboard_view == "demand") echo "active";?>"><a  class="navlink"  href="/demand">Campaign</a>
              </li>
              <li class="divider-vertical"></li>
              <?php endif;?>
              <?php if (($user_data != null && $user_data->PublisherInfoID != null) || $userRole=='admin' || $userRole=='superadmin'): ?>
              <li class="<?php if($home_dashboard_view == "publisher") echo "active";?>"><a class="navlink"   href="/publisher">Websites</a></li>
              <li class="divider-vertical"></li>
              <?php endif;?>
              <li class="<?php if($home_dashboard_view == "report") echo "active";?>"><a class="navlink"   href="/report">Report</a></li>
              <li class="divider-vertical"></li>
              <?php endif;?>
                <?php if ($this->Login_bool() == true):?>
                  <li class="<?php if($_SERVER['REQUEST_URI'] == "/users/account") echo "active";?>"><a class="navlink" href="/users/account">Account Settings</a></li>
                  <?php if($userRole=='admin' || $userRole=='superadmin'): ?>
                  <li class="divider-vertical"></li>
                  <li class="<?php if($_SERVER['REQUEST_URI'] == "/users/publishers") echo "active";?>"><a class="navlink" href="/users/publishers">Publisher List</a></li>
                  <li class="divider-vertical"></li>
                  <li class="<?php if($_SERVER['REQUEST_URI'] == "/users/customers") echo "active";?>"><a class="navlink" href="/users/customers">Customer List</a></li>
                  <li class="divider-vertical"></li>
                  <li class="<?php if($_SERVER['REQUEST_URI'] == "/websites") echo "active";?>"><a class="navlink" href="/websites">Websites List</a></li> 
                  <?php endif;?>
                  <!--<li><a href="<?php //echo $this->url('login/process', array('action'=>'logout')); ?>">Logout</a></li>-->
                <?php else:  ?>
                <li class="<?php if($home_dashboard_view == "login") echo "active";?>" ><a  class="navlink"  href="<?php echo $this->url('login/process', array('action'=>'login')); ?>">Login</a></li>
                <?php endif;  ?>
            </ul>
        </div>
       </div>
    </div>
<div class="container bottom-container">
  <div class="compLayout<?php echo $extra_main_content_class; ?>" id="main-container">
    <?php if (isset($child) && $child != null && isset($child->user_id_list)):?>
    <h4 class="headbreadcrumb blue-color">
      <?php if (isset($child->header_title)):
		echo $child->header_title;
	 endif; ?>
      <br clear="all">
      <div class="pull-right black-color negative-margin">
        <?php 
        // If Admin, show which account you are creating for.
            if($child->impersonate_id == "0" || $child->impersonate_id == null || !isset($child->user_id_list[intval($child->effective_id)])):
                echo "<img src='/images/man-icon.png' /> " . $child->true_user_name;
            else:
                echo "<img src='/images/man-icon.png' /> " . $child->user_id_list[intval($child->effective_id)];
            	if ($child->is_admin === true):
            		echo " (" . $child->effective_id . ")";
            	endif;
            endif;
        ?>
      </div>
      <div class="pull-right"> <br clear="all">
      </div>
    </h4>
    <?php endif; ?>
    <?php echo $this->content; ?> </div>
</div>
<!-- /container -->
</div>
<footer class="footer">
  <div class="container">
    <div class="row mt10">
        <a  href="/company">Company</a> 
        <div class="sep"></div>
        <a  href="/company/press">Press</a>
        <div class="sep"></div>
        <a  href="/company/leadership">Leadership</a>
        <div class="sep"></div>
        <a  href="/company/testimonials">Testimonials</a> 
        <div class="sep"></div>
        <a  href="/company/jobs">jobs</a>
        <div class="sep"></div>
        <a href="#" onclick="return termsWindow('/legal/privacy', 600, 400);">Privacy Policy</a>
        <div class="sep"></div>
        <a href="#" onclick="return termsWindow('/legal/terms', 600, 400);">Terms of Use</a>
        <div class="sep"></div>
        <a href="#" onclick="return termsWindow('/legal/publisheragreement', 600, 400);">Publisher Agreement</a>
        <div class="sep"></div>
        <a href="#" onclick="return termsWindow('/legal/demandagreement', 600, 400);">Demand Customer Agreement</a>
        <div class="sep"></div>
        <a  href="#" onclick="return helpWindow('https://nginad.atlassian.net/wiki/display/NGIN/Using+NginAd+Ad+Server', 1200,1000);">Help Center</a>
        <div class="sep"></div> 
        <a  href="#" onclick="return helpWindow('https://nginad.zendesk.com', 1200,1000);">Support Tickets</a> 
    </div>
    <div class="row mt10 mb20 copyrights">
        <div class="pull-left copy"> 
        	&copy; 2013 - <?php echo date('Y') ?> by CDNPAL NGINAD. <?php echo $this->translate('All rights reserved.') ?>
        </div>
    </div>
  </div>
</footer>
<?php echo $this->inlineScript() ?> <?php echo file_get_contents("module/DashboardManager/view/support/support.js"); ?>
</body>
</html>
